### ISSUE TITLE
unexpected keyword argument on datacentred

### ISSUE THREAD

**Issue by rptaylor** [hep-gc/cloud-scheduler#383] opened 2015-06-30 21:31 UTC
2015-06-30 23:23:32,233 - ERROR - Scheduler - Unhandled exception while creating vm on datacentred: **init**() got an unexpected keyword argument 'retry_after'

Is it maybe different behaviour from a newer OpenStack version?

**Comment by rptaylor** [comment] 2015-09-01 17:40
Peter thinks datacentred is running Havana. The same problem was also observed on CERN Openstack so I don't think it's new behaviour related to a different Openstack version.

**Comment by mhpx** [comment] 2015-09-01 17:42
retry_after isn't anything from CS... at least not in the CS code. It probably comes from the internal httplib or novaclient version differences.

**Comment by rptaylor** [comment] 2015-09-01 17:48
Okay, so how can it be fixed?

**Comment by mhpx** [comment] 2015-09-01 17:50
try updating the novaclient module ?

**Comment by mhpx** [comment] 2015-09-01 17:59
Looks like this/was a known issue in nova api: https://git.openstack.org/cgit/openstack/python-novaclient/commit/?id=310b87ecbb8cd4c82a460781cf7b4e9e79c604d9 
So the fix may be they need to upgrade their openstack

**Comment by rptaylor** [comment] 2015-09-02 20:09
Okay, so you're saying either a bug in the python-novaclient on the Cloud Scheduler side, or a bug in nova-api on the Openstack side may be responsible, and fixing either of them could resolve the issue.

**Comment by mhpx** [comment] 2015-09-02 20:13
if datacentred is running Havana? then you'd probably need to downgrade the python novaclient for CS. (Of course this may cause a problem on clouds running a newer openstack) So the way to resolve the issue is to run a version of openstack that isn't in EOL.

**Comment by ptrlv** [comment] 2015-09-03 09:35
To confirm, they're on Juno and moving to Kilo in the next month or so.

**Comment by rptaylor** [comment] 2015-09-03 20:54
Hmm that's pretty recent. I guess we'll see what happens when they upgrade to Kilo...

**Closed** 2017-01-30 18:46 UTC
